/**
 * Creche YAML
 * This is Vivos Creche API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: smulhall79@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Child } from './child';
import { Group } from './group';
import { Guardian } from './guardian';
import { Location } from './location';


export interface ChildRequest {
    child?: Child;
    guardians?: Array<Guardian>;
    groups?: Array<Group>;
    location?: Location;
}
