/**
 * Creche YAML
 * This is Vivos Creche API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: smulhall79@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { IngredientType } from './ingredientType';
import { MealType } from './mealType';


export interface Ingredient {
    id?: number;
    name?: string;
    type?: IngredientType;
    checked?: boolean;
    usedIn?: Array<MealType>;
}
