/**
 * Creche YAML
 * This is Vivos Creche API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: smulhall79@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Invoice {
    id?: number;
    paid?: boolean;
    amount?: number;
    dueDate?: string;
    createDate?: string;
    customer?: string;
    items?: any;
}
