/**
 * Creche YAML
 * This is Vivos Creche API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: smulhall79@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TimeSheet } from './timeSheet';


export interface StaffPayroll {
    id?: number;
    name?: string;
    hourlyRate?: number;
    totalHours?: number;
    totalPaidHours?: number;
    totalPaidBreaks?: number;
    totalUnPaidBreaks?: number;
    totalMoney?: number;
    startDate?: string;
    endDate?: string;
    timeSheets?: Array<TimeSheet>;
}
