/**
 * Creche YAML
 * This is Vivos Creche API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: smulhall79@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TimeSheetType } from './timeSheetType';


export interface TimeSheetEntry {
    id?: number;
    notes?: string;
    type?: TimeSheetType;
    time?: string;
    locationId?: number;
    _default?: boolean;
    userId?: number;
    device?: string;
}
