/**
 * Creche YAML
 * This is Vivos Creche API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: smulhall79@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TimeCalcs } from './timeCalcs';
import { TimeSheetEntry } from './timeSheetEntry';


export interface TimeSheet {
    id?: number;
    name?: string;
    date?: string;
    startTime?: string;
    endTime?: string;
    calcs?: TimeCalcs;
    group?: string;
    location?: number;
    gender?: TimeSheet.GenderEnum;
    attendance?: Array<TimeSheetEntry>;
}
export namespace TimeSheet {
    export type GenderEnum = 'MALE' | 'FEMALE';
    export const GenderEnum = {
        MALE: 'MALE' as GenderEnum,
        FEMALE: 'FEMALE' as GenderEnum
    }
}
