/**
 * Creche YAML
 * This is Vivos Creche API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: smulhall79@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Transaction {
    id?: number;
    uuid?: string;
    type?: string;
    bankAccount?: string;
    lodgementNo?: string;
    lodgementDate?: string;
    date?: string;
    paymentType?: string;
    supplier?: string;
    refNo?: string;
    customer?: string;
    notes?: string;
    credit?: number;
    debit?: number;
    balance?: number;
    currency?: string;
    vatCode?: string;
    category?: string;
    subCategory?: string;
    fileUrl?: string;
}
